### ISSUE TITLE
[BUG] Erro ao carregar etapas logo no inicio da renderização da pagina

### ISSUE THREAD

**Issue by AmandaaMoura** [fga-eps-mds/2023-2-CAPJu-Doc#102]
**Descreva o bug**

Ao iniciar a página de etapas aparece "erro ao carregar as etapas", com o usuario nao tendo nenhuma etapa cadastrada 

**Como reproduzir**
Passos para reproduzir o comportamento:
1. Go to 'Etapas'
2. If none stage created 
3. See error

**Comportamento esperado**
Mesmo que o usuário não tivesse alguma etapa cadastrado, este erro nao deveria aparecer

**Screenshots**

![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/110147898/24748603-e523-4f5c-8bd2-39f5339a787e)

**Comment by brendavsantos** [comment]
Erro foi arrumado em algum outro PR
