### ISSUE TITLE
[BUG] checkbox invisível na pag de processos

### ISSUE THREAD

**Issue by AmandaaMoura** [fga-eps-mds/2023-2-CAPJu-Doc#103]
**Descreva o bug**

Checkbox de "Mostrar processos interrompidos/concluídos" está invisel antes de ser selecionada
 
**Como reproduzir**
Passos para reproduzir o comportamento:
1. Go to 'Processos'
2. See error

**Comportamento esperado**
As duas checkbox presentes na tela deveriam aparecer mesmo antes de serem selecionadas

**Screenshots**
![carrregamento-normal-na-pag-processos](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/110147898/831ccde4-eea0-4da6-9731-b5ef8fe05885)
![checkbox-apos-ser-selecionada](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/110147898/9d4c12a6-4232-4ce5-ab9a-bc687f613972)

**Comment by brendavsantos** [comment]
Resolvido no PR: https://github.com/fga-eps-mds/2023-2-CAPJu-Front/pull/34
no arquivo src/pages/Processes/index.tsx
