### ISSUE TITLE
[BUG] Processos com data efetiva fora do intervalo de 2 anos a partir da data atual

### ISSUE THREAD

**Issue by LeanArs** [fga-eps-mds/2023-2-CAPJu-Doc#121]
**Descreva o bug**
Ao abrir o relatório "Quantidade de Processos Concluídos / Interrompidos", todos os processos são listados, quando na verdade deveria ser buscado apenas os processos com data efetiva dentro do intervalo de 2 anos a partir da data atual.

**Como reproduzir**
Antes de seguir o passo a passo, certifique-se de que possuí um processo finalizado ou concluído a mais de 2 anos.
Passos para reproduzir o comportamento:
1. Acessar página "Estatísticas"
2. Abrir accordeon de "Visualizar Quantidade de Processos Concluídos / Interrompidos"
3. Busque na paginação o processo antigo

**Comportamento esperado**
Ao abrir o accordeon, deve-se mostrar apenas os processos com data efetiva dentro do intervalo de 2 anos a partir da data atual.

**Screenshots**
Processo 0 no banco de dados com data efetiva para 01/12/2020:
![image1](https://i.imgur.com/hv4g3QI.png)

Processo 0 sendo mostrado no relatório:
![image1](https://i.imgur.com/noLgfQ4.png)

**Comment by brendavsantos** [comment]
Vou fazer esse

**Comment by brendavsantos** [comment]
https://github.com/fga-eps-mds/2023-2-CAPJu-Front/pull/61
