### ISSUE TITLE
[BUG] Hyperlink "Sobre" não redireciona página

### ISSUE THREAD

**Issue by LeanArs** [fga-eps-mds/2023-2-CAPJu-Doc#123]
**Descreva o bug**
Ao clicar no botão "sobre" enquanto logado no sistema, a página é recarregada.

**Como reproduzir**
Passos para reproduzir o comportamento:
1. Realize login
2. Clique em "Sobre"

**Comportamento esperado**
É esperado que a página seja redirecionada para a página de "sobre"

**Contexto adicional**
É importante que ao ser redirecionado, o usuário possam voltar ao sistema sem que seja necessário logar novamente. De tal forma, seria necessário um botão de "voltar" ou algo parecido.

**Comment by JongaMatos** [comment]
Corrigido em outra issue
