### ISSUE TITLE
[BUG] Paginação Processos

### ISSUE THREAD

**Issue by LeanArs** [fga-eps-mds/2023-2-CAPJu-Doc#128]
**Descreva o bug**
Paginação da página de Processos não é resetada ao selecionar "Processos apenas processos com prioridade legal" ou "Mostrar processos concluídos / interrompidos". De tal forma, se você estiver na página 2 de processos e clicar, por exemplo, em "Mostrar processos concluídos / interrompidos", será mostrado na tela a página 2 dos processos concluídos e interrompidos.

**Como reproduzir**
Antes de reproduzir o erro, certifique-se de que possui processos o suficiente para que seja possível passar as páginas.
Passos para reproduzir o comportamento:
1. Acessar página "Etapas"
2. Passe para qualquer outra página
3. Selecione o checkbox "Processos apenas processos com prioridade legal" ou "Mostrar processos concluídos / interrompidos"
4. Veja o erro

**Comportamento esperado**
Era esperado que ao mudar o estado de qualquer um dos select boxes, o pagination voltasse para 1 juntamente com sua respectiva página.

**Comment by brendavsantos** [comment]
PR que resolve: https://github.com/fga-eps-mds/2023-2-CAPJu-Front/pull/35
