### ISSUE TITLE
[BUG] Ao concluir processo a rastreabilidade não atualiza

### ISSUE THREAD

**Issue by Denniel-sudo** [fga-eps-mds/2023-2-CAPJu-Doc#132]
**Descreva o bug**

**Como reproduzir**
Passos para reproduzir o comportamento:

**Comportamento esperado**

**Screenshots**

**Desktop (complete as informações abaixo):**

**Contexto adicional**

**Comment by ngm1450** [comment]
[PR](https://github.com/fga-eps-mds/2023-2-CAPJu-ProcessManagement-Service/pull/28)
