### ISSUE TITLE
[BUG] Navbar não atualiza ao recarregar página

### ISSUE THREAD

**Issue by LeanArs** [fga-eps-mds/2023-2-CAPJu-Doc#144]
**Descreva o bug**
Navbar não atualiza ao recarregar página.

**Como reproduzir**
Passos para reproduzir o comportamento:
1. Acesse qualquer página que não seja "Unidades"
2. Recarregue a página
3. Observe que a página selecionada na navbar ainda é a página no qual estava, mas que agora você está na página "Unidades"

**Comportamento esperado**
Era esperado que ao recarregar a página, a navbar também selecionasse a página "Unidades"

**Comment by ngm1450** [comment]
[PR](https://github.com/fga-eps-mds/2023-2-CAPJu-Front/pull/36)
