### ISSUE TITLE
[Bug] Pesquisar etapa após criação

### ISSUE THREAD

**Issue by JongaMatos** [fga-eps-mds/2023-2-CAPJu-Doc#154]
**Descreva o bug**

![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/54087048/5a784334-3d0d-4004-8791-3da16ab2fb01)

**Comment by brendavsantos** [comment]
Não foi possível reproduzir, pedir pra ele tentar fazer de novo depois
