### ISSUE TITLE
[BUG] Não é possível editar etapa

### ISSUE THREAD

**Issue by LeanArs** [fga-eps-mds/2023-2-CAPJu-Doc#169]
**Descreva o bug**

**Como reproduzir**
Passos para reproduzir o comportamento:

**Comportamento esperado**

**Screenshots**

**Desktop (complete as informações abaixo):**

**Contexto adicional**

**Comment by brendavsantos** [comment]
https://github.com/fga-eps-mds/2023-2-CAPJu-ProcessManagement-Service/pull/45
