### ISSUE TITLE
[BUG] Não é possível editar apelido de fluxo já iniciado

### ISSUE THREAD

**Issue by LeanArs** [fga-eps-mds/2023-2-CAPJu-Doc#170]
**Descreva o bug**

**Como reproduzir**
Passos para reproduzir o comportamento:

**Comportamento esperado**

**Screenshots**

**Desktop (complete as informações abaixo):**

**Contexto adicional**

**Comment by brendavsantos** [comment]
https://github.com/fga-eps-mds/2023-2-CAPJu-Front/pull/71
