### ISSUE TITLE
Recuperação de senha

### ISSUE THREAD

**Issue by brendavsantos** [fga-eps-mds/2023-2-CAPJu-Doc#175]
Anteriormente, conversas sobre a recuperação de senha não foram levantadas então não fez parte do backlog da equipe em momento algum. Mas visando entregar um produto o mais completo e funcional possível, a funcionalidade foi refeita (pois não funcionava/existia) e será disponibilizada também como uma das ultimas entregas.

Tasks:
- [x]  Identificar os requisitos de segurança para a nova senha (complexidade, comprimento, etc.).
- [x] Desenvolver uma interface de usuário para alteração de senha.
- [x] Enviar o link para alteração via e-mail
- [x] Implementar a validação de senha para garantir que a nova senha atenda aos requisitos de segurança.

Critérios de aceitação:
- [ ] O usuário deve ser capaz de inserir e confirmar a nova senha.
- [ ] A nova senha deve atender aos critérios de segurança estabelecidos.
- [ ] Deve existir um registro auditável de todas as tentativas e alterações de senha.

**Comment by brendavsantos** [comment]
https://github.com/fga-eps-mds/2023-2-CAPJu-User-Service/pull/18

**Comment by well1981** [comment]
Validada a implementação.
