### ISSUE TITLE
US18 - Criptografar autenticação

### ISSUE THREAD

**Issue by brendavsantos** [fga-eps-mds/2023-2-CAPJu-Doc#5]
## Descrição da História
Eu, como usuário, gostaria que minha autenticação seja criptografada de forma segura para poder confiança na segurança dos meus dados e informações pessoais, garantindo que apenas eu ou autorizadas tenham acesso ao meu perfil e informações sensíveis.

## Tasks
As seguintes tasks  devem ser completas para concluir a história:
- [x] [Criptografar a senha que vai ser salva no banco no momento do cadastro](https://github.com/fga-eps-mds/)
- [x] [Conferir se a hash da senha é a mesma no momento do login](https://github.com/fga-eps-mds/)

**Comment by well1981** [comment]
Validada a implementação.
