### ISSUE TITLE
Aumento de cobertura dos testes do Frontend services

### ISSUE THREAD

**Issue by JongaMatos** [fga-eps-mds/2023-2-CAPJu-Doc#97]
Aumentar a cobertura de testes do frontend

**Comment by JongaMatos** [comment]
![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/54087048/f86e56f6-6455-47d3-ab19-b8dd91456443)

**Comment by brendavsantos** [comment]
https://github.com/fga-eps-mds/2023-2-CAPJu-Front/pull/75
